COMPOSE := docker compose

.PHONY: help up up-build down restart logs logs-api ps build migrate migrate-up migrate-down shell bash ui ui-build ui-install health clean nuke test lint

help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2}'

up: ## Start all services (detached)
	$(COMPOSE) up -d

up-build: ## Rebuild and start all services
	$(COMPOSE) up -d --build

down: ## Stop all services
	$(COMPOSE) down

restart: ## Restart all services
	$(COMPOSE) restart

logs: ## Tail logs (all services)
	$(COMPOSE) logs -f

logs-api: ## Tail backend logs only
	$(COMPOSE) logs -f backend

ps: ## Show running containers
	$(COMPOSE) ps

build: ## Build service images
	$(COMPOSE) build

migrate: ## Create an autogenerated migration and apply it
	$(COMPOSE) exec backend alembic revision --autogenerate -m "auto" && \
	$(COMPOSE) exec backend alembic upgrade head

migrate-up: ## Apply pending migrations
	$(COMPOSE) exec backend alembic upgrade head

migrate-down: ## Roll back the latest migration
	$(COMPOSE) exec backend alembic downgrade -1

shell: ## Open a Python shell in the backend container
	$(COMPOSE) exec backend python

bash: ## Open a bash shell in the backend container
	$(COMPOSE) exec backend bash

ui: ## Start the frontend dev server locally
	cd frontend && npm run dev

ui-build: ## Build the frontend bundle
	cd frontend && npm run build

ui-install: ## Install frontend dependencies
	cd frontend && npm install

lint: ## Run lightweight code checks
	$(COMPOSE) exec backend python -m compileall app

test: ## Run backend tests
	$(COMPOSE) exec backend pytest

health: ## Check backend health endpoint
	@curl -sf http://localhost:8000/health | python3 -m json.tool || echo "API not reachable"

clean: ## Stop services and remove volumes
	$(COMPOSE) down -v

nuke: ## Full reset of containers, volumes, and local images
	$(COMPOSE) down -v --rmi local
